version: '3'
services:
  webserver:
    container_name: webserver
    env_file:
      - .env
    build:
      context: dev/servers/web
      args:
        HOST_USER_ID: ${HOST_USER_ID:-0}
        HOST_GROUP_ID: ${HOST_GROUP_ID:-0}
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
      - ./dev/vhost:/etc/apache2/sites-enabled
    networks:
      app_net:

  database:
    container_name: database
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    volumes:
      - database:/var/lib/mysql
    networks:
      app_net:

  mailserver:
    container_name: mailserver
    image: schickling/mailcatcher
    ports:
      - 1080:1080
    networks:
      app_net:

volumes:
  database:
    driver: local

networks:
  app_net:
    driver: bridge

